# Generated by Django 4.2.11 on 2024-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=64)),
                ('company_a', models.CharField(max_length=255)),
                ('company_b', models.CharField(max_length=255)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('purchase_description', models.TextField()),
                ('purchase_detail', models.TextField()),
                ('total_fee', models.TextField()),
                ('bankName', models.TextField()),
                ('accountName', models.TextField()),
                ('accountNum', models.TextField()),
                ('contract_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_contract',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=64)),
                ('company_a', models.CharField(max_length=255)),
                ('company_b', models.CharField(max_length=255)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('service_description', models.TextField()),
                ('service_detail', models.TextField()),
                ('fee', models.TextField()),
                ('payment_method', models.TextField()),
                ('contract_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_contract',
                'managed': True,
            },
        ),
    ]
